OPENAI_API_KEY = "sk-vPw08kOHKyLlU6Fn64D0Dc055179413f89CbF73b485f6d1c"
OPENAI_MODEL = "gpt-4o"
BASE_URL = "https://api.gpt.ge/v1/"

NEO4J_URI = "neo4j+s://1a6c6f46.databases.neo4j.io"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "ry5LD0-vg5kH58P3ghXZqsYYx3UEzk7Ch4i-KveUa6k"